server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/vehiculos/**
          filters:
            - RewritePath=/vehiculos/(?<segment>.*), /$\{segment}
        - id: reparacion-service
          uri: lb://reparacion-service
          predicates:
            - Path=/reparaciones/**
          filters:
            - RewritePath=/reparaciones/(?<segment>.*), /$\{segment}
        - id: historial-service
          uri: lb://historial-service
          predicates:
            - Path=/historial/**
          filters:
            - RewritePath=/historial/(?<segment>.*), /$\{segment}
        - id: autofix-service
          uri: lb://autofix-service
          predicates:
            - Path=/reportes/**
          filters:
            - RewritePath=/reportes/(?<segment>.*), /$\{segment}