apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_VEHICULOS: cG9zdGdyZXM=
  DB_PASSWORD_VEHICULOS: aW50aWhha3U0NTIz
  DB_USER_REPARACIONES: cG9zdGdyZXM=
  DB_PASSWORD_REPARACIONES: aW50aWhha3U0NTIz
  DB_USER_HISTORIAL: cG9zdGdyZXM=
  DB_PASSWORD_HISTORIAL: aW50aWhha3U0NTIz