apiVersion: apps/v1
kind: Deployment
metadata:
  name: reparacion-service-deployment
  labels:
    app: reparacion-service-deployment
spec:
  selector:
    matchLabels:
      app: reparacion-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reparacion-service-deployment
    spec:
      containers:
        - name: reparacion-service
          image: thecariah/reparacion-service
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPARACIONES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPARACIONES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPARACIONES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPARACIONES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPARACIONES